"""add job_openings, applications, user_job_preferences tables

Revision ID: bc05a5432f12
Revises: 001
Create Date: 2026-02-16 15:25:57.334756
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc05a5432f12'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_openings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=True),
    sa.Column('is_remote', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_openings_source')
    )
    op.create_index(op.f('ix_job_openings_company_id'), 'job_openings', ['company_id'], unique=False)
    op.create_table('user_job_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('target_seniority', sa.String(length=100), nullable=True),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('open_to_remote', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('job_search_status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("job_search_status IN ('active', 'passive', 'paused')", name='ck_user_job_preferences_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_job_preferences_user')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('job_opening_id', sa.UUID(), nullable=True),
    sa.Column('match_result_id', sa.UUID(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'message_sent', 'responded', 'interview_scheduled', 'interviewed', 'offer_received', 'offer_accepted', 'rejected', 'withdrawn', 'no_response')", name='ck_applications_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('user_job_preferences')
    op.drop_index(op.f('ix_job_openings_company_id'), table_name='job_openings')
    op.drop_table('job_openings')
    # ### end Alembic commands ###
