"""Feed system models for proactive engagement.

FeedItem: Background-generated insights, alerts, and prompts that appear
in the user's activity feed and power push notifications.

FeedItemInteraction: Full interaction history for recommendation tuning.

ContactFreshnessSignal: User-confirmed data about contacts (still at company,
relationship type, recency) — seeds the cross-user trust graph.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models import Base


class FeedItem(Base):
    """A single item in the user's activity feed.

    Generated by background Celery tasks, surfaced in-app and via email digest.
    Each item has a type, priority, action URL, and lifecycle timestamps
    (seen/acted/dismissed) that power engagement analytics.

    Medium-term value: feed interaction data trains relevance ranking.
    Long-term value: outcome-linked feed items prove platform ROI for B2B pitch.
    """

    __tablename__ = "feed_items"
    __table_args__ = (
        CheckConstraint(
            "item_type IN ("
            "'job_alert', 'contact_update', 'enrichment_prompt', "
            "'marketplace_signal', 'outcome_check', 'platform_activity', "
            "'network_insight', 'follow_up_nudge')",
            name="ck_feed_items_type",
        ),
        CheckConstraint(
            "priority BETWEEN 1 AND 100",
            name="ck_feed_items_priority",
        ),
        # Primary query: unseen items for a user, newest first
        Index("idx_feed_items_user_unseen", "user_id", "seen_at", "created_at"),
        # Dedup: prevent duplicate feed items of same type for same target
        Index(
            "idx_feed_items_dedup",
            "user_id",
            "item_type",
            "dedup_key",
            unique=True,
            postgresql_where="dismissed_at IS NULL AND dedup_key IS NOT NULL",
        ),
        # Cleanup: expired items
        Index("idx_feed_items_expires", "expires_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # What kind of feed item
    item_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)

    # Display content
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    body: Mapped[str | None] = mapped_column(Text)
    icon: Mapped[str | None] = mapped_column(String(50))  # emoji or icon key

    # Action deep link
    action_url: Mapped[str | None] = mapped_column(String(500))
    action_label: Mapped[str | None] = mapped_column(String(100))

    # Ranking
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=50)

    # Flexible payload per item type (company_id, contact_id, job_ids, etc.)
    metadata_: Mapped[dict | None] = mapped_column("metadata", JSONB)

    # Dedup key — e.g. "job_alert:company_uuid:2026-02-20" prevents duplicates
    dedup_key: Mapped[str | None] = mapped_column(String(500))

    # Lifecycle timestamps
    seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    acted_on_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    dismissed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Was this item included in an email digest?
    emailed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    user: Mapped["User"] = relationship()
    interactions: Mapped[list["FeedItemInteraction"]] = relationship(
        back_populates="feed_item", cascade="all, delete-orphan"
    )


class FeedItemInteraction(Base):
    """Granular interaction log for feed items.

    Separate from FeedItem lifecycle timestamps because a user may interact
    with the same item multiple times (view, click, dismiss, re-view).
    This table is the training data for future relevance ranking.
    """

    __tablename__ = "feed_item_interactions"
    __table_args__ = (
        CheckConstraint(
            "interaction_type IN ('view', 'click', 'dismiss', 'share', 'snooze')",
            name="ck_feed_item_interactions_type",
        ),
        Index(
            "idx_feed_interactions_item",
            "feed_item_id",
            "created_at",
        ),
        Index(
            "idx_feed_interactions_user_type",
            "user_id",
            "interaction_type",
            "created_at",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    feed_item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("feed_items.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    interaction_type: Mapped[str] = mapped_column(String(20), nullable=False)
    # Where the interaction came from (in_app, email_click, push_notification)
    source: Mapped[str | None] = mapped_column(String(50))
    metadata_: Mapped[dict | None] = mapped_column("metadata", JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    feed_item: Mapped["FeedItem"] = relationship(back_populates="interactions")


class ContactFreshnessSignal(Base):
    """User-confirmed data about a contact's current state.

    Collected via enrichment prompts in the feed. Each signal confirms or
    updates one aspect of a contact: still at company, relationship type,
    last interaction, willingness to refer.

    Medium-term value: improves warm score accuracy and match quality.
    Long-term value: seeds the directional trust graph (who would refer whom).
    Cross-user value: if 3 users confirm "Sarah left Stripe," confidence
    is high enough to flag stale data across all vaults (anonymized).
    """

    __tablename__ = "contact_freshness_signals"
    __table_args__ = (
        CheckConstraint(
            "signal_type IN ("
            "'still_at_company', 'relationship_type', 'last_interaction', "
            "'would_refer', 'contact_moved', 'role_changed')",
            name="ck_freshness_signal_type",
        ),
        # Latest signal per contact per type
        Index(
            "idx_freshness_signals_latest",
            "contact_id",
            "signal_type",
            "created_at",
        ),
        # Cross-user aggregation: how many users confirmed same thing
        # Uses name_company_hash (SHA-256 of normalized name+company) for privacy
        Index(
            "idx_freshness_signals_cross_user",
            "name_company_hash",
            "signal_type",
            "created_at",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    contact_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("contacts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)

    # The signal value — semantics depend on signal_type:
    # still_at_company: {"confirmed": true/false, "new_company": "..."}
    # relationship_type: {"type": "colleague|manager|friend|alumni|investor|acquaintance"}
    # last_interaction: {"recency": "last_month|last_quarter|last_year|2_plus_years"}
    # would_refer: {"likelihood": "definitely|probably|unsure|no"}
    # contact_moved: {"old_company": "...", "new_company": "...", "new_title": "..."}
    # role_changed: {"old_title": "...", "new_title": "..."}
    signal_value: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Privacy-safe cross-user hash for aggregation
    # SHA-256(lowercase(full_name) + "|" + lowercase(company_name))
    name_company_hash: Mapped[str | None] = mapped_column(String(64), index=True)

    # Was this signal applied back to the contact record?
    applied_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Did this come from a feed prompt, manual edit, or API enrichment?
    source: Mapped[str] = mapped_column(
        String(50), nullable=False, server_default="feed_prompt"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    user: Mapped["User"] = relationship()
    contact: Mapped["Contact"] = relationship()


class FreshnessPropagationLog(Base):
    """Log of cross-user freshness signal propagation events.

    Privacy: NO user_ids stored. Only hashed identifiers and aggregate counts.
    Records when consensus was reached and how many contacts were updated.
    """

    __tablename__ = "freshness_propagation_log"
    __table_args__ = (
        Index(
            "idx_propagation_log_hash_type",
            "name_company_hash",
            "signal_type",
            "created_at",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name_company_hash: Mapped[str] = mapped_column(
        String(64), nullable=False, index=True
    )
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)
    consensus_value: Mapped[dict] = mapped_column(JSONB, nullable=False)
    source_count: Mapped[int] = mapped_column(Integer, nullable=False)
    contacts_updated: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
